// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbj8IAj2rb9e5sOScWDrbJc6wmJ39NJQo',
    appId: '1:414335552159:web:9dd64667676e36c5b070aa',
    messagingSenderId: '414335552159',
    projectId: 'iconica-training-system',
    authDomain: 'iconica-training-system.firebaseapp.com',
    databaseURL: 'https://iconica-training-system-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iconica-training-system.appspot.com',
    measurementId: 'G-DVHT43C7G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz9I4pdPszLYkA1V5ArtN3UkMDb3fqLUk',
    appId: '1:414335552159:android:19dd5f41e0a0bbd3b070aa',
    messagingSenderId: '414335552159',
    projectId: 'iconica-training-system',
    databaseURL: 'https://iconica-training-system-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iconica-training-system.appspot.com',
  );
}
